version: "3.5"
services:
  app:
    container_name: "${CONTAINER_NAME}"
    restart: on-failure
    build: .
    image: "${CONTAINER_NAME}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "${M_PORT}:${PORT}"
networks:
  default:
    name: "${NETWORK_NAME}"
