version: '3.2'
services:
  mysql:
    platform: linux/x86_64
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    image: mysql
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - './${DB_VOLUME}:/var/lib/mysql'
    command: mysqld --default-authentication-plugin=mysql_native_password
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    restart: on-failure
    image: redis:6.0.8
    ports:
      - '${REDIS_PORT}:6379'
networks:
  default:
    name: '${NETWORK_NAME}'
